2022-02-24 10:34:49,962 - root - INFO - New connection from: 192.168.56.1
2022-02-24 10:34:49,963 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-24 10:35:22,624 - root - INFO - New connection from: 192.168.56.1
2022-02-24 10:35:22,627 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-24 10:35:22,652 - paramiko.transport - INFO - Auth rejected (none).
2022-02-24 10:35:22,653 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-24 10:35:24,582 - root - INFO - new client credentials (192.168.56.1): username: kali, password: kk
2022-02-24 10:35:24,583 - paramiko.transport - INFO - Auth granted (password).
2022-02-24 10:35:24,584 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-24 10:35:24,585 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-24 10:35:24,585 - root - INFO - Client compression (192.168.56.1): none
2022-02-24 10:35:24,585 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-24 10:35:24,585 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-24 10:35:26,644 - root - INFO - Command receied (192.168.56.1): dir
2022-02-24 10:35:26,647 - root - INFO - Response -> honeypot (192.168.56.1): 
2022-02-24 10:35:29,058 - root - INFO - Command receied (192.168.56.1): cd
2022-02-24 10:35:29,059 - root - INFO - Response -> honeypot (192.168.56.1): 
2022-02-24 10:35:32,777 - root - INFO - Command receied (192.168.56.1): exit
2022-02-24 10:35:32,777 - root - INFO - Connection closed (via exit command): 192.168.56.1

2022-02-24 10:35:32,780 - paramiko.transport - INFO - Disconnect (code 11): disconnected by user
2022-02-24 10:43:13,725 - root - INFO - New connection from: 192.168.56.1
2022-02-24 10:43:13,728 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-24 10:43:13,749 - paramiko.transport - INFO - Auth rejected (none).
2022-02-24 10:43:13,749 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-24 10:43:15,273 - root - INFO - new client credentials (192.168.56.1): username: kali, password: ok
2022-02-24 10:43:15,273 - paramiko.transport - INFO - Auth granted (password).
2022-02-24 10:43:15,275 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-24 10:43:15,275 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-24 10:43:15,275 - root - INFO - Client compression (192.168.56.1): none
2022-02-24 10:43:15,276 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-24 10:43:15,276 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-24 10:43:17,513 - root - INFO - Command receied (192.168.56.1): cd
2022-02-24 10:43:17,513 - root - INFO - Response -> honeypot (192.168.56.1): 
2022-02-24 10:43:19,646 - root - INFO - Command receied (192.168.56.1): dir
2022-02-24 10:43:19,652 - root - INFO - Response -> honeypot (192.168.56.1): 
2022-02-24 10:43:24,051 - root - INFO - Command receied (192.168.56.1): exit
2022-02-24 10:43:24,051 - root - INFO - Connection closed (via exit command): 192.168.56.1

2022-02-24 10:43:24,053 - paramiko.transport - INFO - Disconnect (code 11): disconnected by user
2022-02-24 10:46:21,625 - root - INFO - New connection from: 192.168.56.1
2022-02-24 10:46:21,631 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-24 10:46:21,650 - paramiko.transport - INFO - Auth rejected (none).
2022-02-24 10:46:21,650 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-24 10:46:22,261 - root - INFO - new client credentials (192.168.56.1): username: kali, password: k
2022-02-24 10:46:22,261 - paramiko.transport - INFO - Auth granted (password).
2022-02-24 10:46:22,263 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-24 10:46:22,264 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-24 10:46:22,264 - root - INFO - Client compression (192.168.56.1): none
2022-02-24 10:46:22,264 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-24 10:46:22,264 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-24 10:46:24,987 - root - INFO - Command receied (192.168.56.1): dir
2022-02-24 10:46:24,991 - root - INFO - Response -> honeypot (192.168.56.1) 
2022-02-24 10:46:28,711 - root - INFO - Command receied (192.168.56.1): exit
2022-02-24 10:46:28,711 - root - INFO - Connection closed (via exit command): 192.168.56.1

2022-02-24 10:46:28,714 - paramiko.transport - INFO - Disconnect (code 11): disconnected by user
2022-02-24 12:22:57,168 - root - INFO - New connection from: 192.168.56.1
2022-02-24 12:22:57,527 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-24 12:22:57,563 - paramiko.transport - INFO - Auth rejected (none).
2022-02-24 12:22:57,563 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-24 12:22:59,853 - root - INFO - new client credentials (192.168.56.1): username: kali, password: kali
2022-02-24 12:22:59,853 - paramiko.transport - INFO - Auth granted (password).
2022-02-24 12:22:59,857 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-24 12:22:59,858 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-24 12:22:59,858 - root - INFO - Client compression (192.168.56.1): none
2022-02-24 12:22:59,858 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-24 12:22:59,858 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-24 12:23:02,188 - root - INFO - Command receied (192.168.56.1): dir
2022-02-24 12:23:02,260 - root - INFO - Response -> honeypot (192.168.56.1) 
2022-02-24 12:23:12,265 - paramiko.transport - INFO - Disconnect (code 11): disconnected by user
2022-02-24 12:24:49,446 - root - INFO - New connection from: 192.168.56.1
2022-02-24 12:24:49,448 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-24 12:24:49,470 - paramiko.transport - INFO - Auth rejected (none).
2022-02-24 12:24:49,470 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-24 12:24:51,586 - root - INFO - new client credentials (192.168.56.1): username: kali, password: kali
2022-02-24 12:24:51,587 - paramiko.transport - INFO - Auth granted (password).
2022-02-24 12:24:51,589 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-24 12:24:51,589 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-24 12:24:51,589 - root - INFO - Client compression (192.168.56.1): none
2022-02-24 12:24:51,590 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-24 12:24:51,590 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-24 12:24:52,865 - root - INFO - Command receied (192.168.56.1): dir
2022-02-24 12:24:52,872 - root - INFO - Response -> honeypot (192.168.56.1) 
2022-02-24 12:24:53,859 - root - INFO - Command receied (192.168.56.1): cd
2022-02-24 12:24:53,859 - root - INFO - Response -> honeypot (192.168.56.1) 
2022-02-24 12:25:00,313 - root - INFO - Command receied (192.168.56.1): exit
2022-02-24 12:25:00,313 - root - INFO - Connection closed (via exit command): 192.168.56.1

2022-02-24 12:25:00,319 - paramiko.transport - INFO - Disconnect (code 11): disconnected by user
2022-02-24 12:32:48,106 - root - INFO - New connection from: 192.168.56.1
2022-02-24 12:32:48,113 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-24 12:32:48,143 - paramiko.transport - INFO - Auth rejected (none).
2022-02-24 12:32:48,143 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-24 12:32:50,704 - root - INFO - new client credentials (192.168.56.1): username: kali, password: kali
2022-02-24 12:32:50,704 - paramiko.transport - INFO - Auth granted (password).
2022-02-24 12:32:50,705 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-24 12:32:50,706 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-24 12:32:50,706 - root - INFO - Client compression (192.168.56.1): none
2022-02-24 12:32:50,706 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-24 12:32:50,706 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-24 12:32:54,836 - root - INFO - Command receied (192.168.56.1): scd
2022-02-24 12:32:59,590 - root - INFO - Command receied (192.168.56.1): ls
2022-02-24 12:33:03,329 - root - INFO - Command receied (192.168.56.1): dell
2022-02-24 12:33:05,032 - root - INFO - Command receied (192.168.56.1): dir
2022-02-24 12:33:05,044 - root - INFO - Response -> honeypot (192.168.56.1) 22-02-2022  03:43 PM    <DIR>          .
24-10-2021  08:24 PM    <DIR>          ..
07-12-2021  08:32 PM    <DIR>          .android
22-09-2020  03:43 PM    <DIR>          3D Objects
15-10-2020  04:12 PM    <DIR>          ansel
07-01-2022  12:44 AM            85,815 battery-report.html
24-10-2021  09:06 PM    <DIR>          Contacts
20-02-2022  08:57 AM    <DIR>          Desktop
27-01-2022  05:42 PM    <DIR>          Documents
23-02-2022  03:52 PM    <DIR>          Downloads
08-12-2021  04:24 PM    <DIR>          Dropbox
08-02-2022  03:44 PM               703 ll.txt
24-10-2021  09:06 PM    <DIR>          Music
30-12-2021  11:42 PM    <DIR>          New Folder
24-12-2021  11:30 PM    <DIR>          Pictures
24-10-2021  09:06 PM    <DIR>          Saved Games
09-01-2022  07:02 PM               142 test.html
31-10-2021  12:27 PM    <DIR>          Videos
              3 File(s)         92,152 bytes
              15 Dir(s)  52,386,295,808 bytes free
2022-02-24 12:33:06,985 - root - INFO - Command receied (192.168.56.1): cd
2022-02-24 12:33:06,986 - root - INFO - Response -> honeypot (192.168.56.1) root
2022-02-24 12:33:12,516 - root - INFO - Command receied (192.168.56.1): dell
2022-02-24 12:33:15,012 - root - INFO - Command receied (192.168.56.1): exit
2022-02-24 12:33:15,012 - root - INFO - Connection closed (via exit command): 192.168.56.1

2022-02-24 12:33:15,020 - paramiko.transport - INFO - Disconnect (code 11): disconnected by user
2022-02-24 12:39:16,392 - root - INFO - New connection from: 192.168.56.1
2022-02-24 12:39:16,394 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-24 12:39:16,431 - paramiko.transport - INFO - Auth rejected (none).
2022-02-24 12:39:16,431 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-24 12:39:18,751 - root - INFO - new client credentials (192.168.56.1): username: kali, password: kali
2022-02-24 12:39:18,752 - paramiko.transport - INFO - Auth granted (password).
2022-02-24 12:39:18,755 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-24 12:39:18,756 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-24 12:39:18,756 - root - INFO - Client compression (192.168.56.1): none
2022-02-24 12:39:18,756 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-24 12:39:18,756 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-24 12:39:25,550 - root - INFO - Command receied (192.168.56.1): sir
2022-02-24 12:39:27,616 - root - INFO - Command receied (192.168.56.1): dir
2022-02-24 12:39:27,626 - root - INFO - Response -> honeypot (192.168.56.1) 22-02-2022  03:43 PM    <DIR>          .
24-10-2021  08:24 PM    <DIR>          ..
07-12-2021  08:32 PM    <DIR>          .android
22-09-2020  03:43 PM    <DIR>          3D Objects
15-10-2020  04:12 PM    <DIR>          ansel
07-01-2022  12:44 AM            85,815 battery-report.html
24-10-2021  09:06 PM    <DIR>          Contacts
20-02-2022  08:57 AM    <DIR>          Desktop
27-01-2022  05:42 PM    <DIR>          Documents
23-02-2022  03:52 PM    <DIR>          Downloads
08-12-2021  04:24 PM    <DIR>          Dropbox
08-02-2022  03:44 PM               703 ll.txt
24-10-2021  09:06 PM    <DIR>          Music
30-12-2021  11:42 PM    <DIR>          New Folder
24-12-2021  11:30 PM    <DIR>          Pictures
24-10-2021  09:06 PM    <DIR>          Saved Games
09-01-2022  07:02 PM               142 test.html
31-10-2021  12:27 PM    <DIR>          Videos
              3 File(s)         92,152 bytes
              15 Dir(s)  52,386,295,808 bytes free
2022-02-24 12:39:29,541 - root - INFO - Command receied (192.168.56.1): cd
2022-02-24 12:39:29,541 - root - INFO - Response -> honeypot (192.168.56.1) root
2022-02-24 12:39:31,895 - root - INFO - Command receied (192.168.56.1): ok
2022-02-24 12:39:35,517 - root - INFO - Command receied (192.168.56.1): exit
2022-02-24 12:39:35,518 - root - INFO - Connection closed (via exit command): 192.168.56.1

2022-02-24 12:39:35,521 - paramiko.transport - INFO - Disconnect (code 11): disconnected by user
2022-02-24 12:44:58,676 - root - INFO - New connection from: 192.168.56.1
2022-02-24 12:44:58,682 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-24 12:44:58,700 - paramiko.transport - INFO - Auth rejected (none).
2022-02-24 12:44:58,700 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-24 12:45:04,653 - root - INFO - new client credentials (192.168.56.1): username: kali, password: kali
2022-02-24 12:45:04,653 - paramiko.transport - INFO - Auth granted (password).
2022-02-24 12:45:04,660 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-24 12:45:04,661 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-24 12:45:04,662 - root - INFO - Client compression (192.168.56.1): none
2022-02-24 12:45:04,662 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-24 12:45:04,662 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-24 12:45:13,125 - root - INFO - Command receied (192.168.56.1): dir
2022-02-24 12:45:13,129 - root - INFO - Response -> honeypot (192.168.56.1) 22-02-2022  03:43 PM    <DIR>          .
24-10-2021  08:24 PM    <DIR>          ..
07-12-2021  08:32 PM    <DIR>          .android
22-09-2020  03:43 PM    <DIR>          3D Objects
15-10-2020  04:12 PM    <DIR>          ansel
07-01-2022  12:44 AM            85,815 battery-report.html
24-10-2021  09:06 PM    <DIR>          Contacts
20-02-2022  08:57 AM    <DIR>          Desktop
27-01-2022  05:42 PM    <DIR>          Documents
23-02-2022  03:52 PM    <DIR>          Downloads
08-12-2021  04:24 PM    <DIR>          Dropbox
08-02-2022  03:44 PM               703 ll.txt
24-10-2021  09:06 PM    <DIR>          Music
30-12-2021  11:42 PM    <DIR>          New Folder
24-12-2021  11:30 PM    <DIR>          Pictures
24-10-2021  09:06 PM    <DIR>          Saved Games
09-01-2022  07:02 PM               142 test.html
31-10-2021  12:27 PM    <DIR>          Videos
              3 File(s)         92,152 bytes
              15 Dir(s)  52,386,295,808 bytes free
2022-02-24 12:45:19,095 - root - INFO - Command receied (192.168.56.1): cd
2022-02-24 12:45:19,096 - root - INFO - Response -> honeypot (192.168.56.1) root
2022-02-24 12:45:22,317 - root - INFO - Command receied (192.168.56.1): exit
2022-02-24 12:45:22,317 - root - INFO - Connection closed (via exit command): 192.168.56.1

2022-02-24 12:45:22,321 - paramiko.transport - INFO - Disconnect (code 11): disconnected by user
2022-02-24 15:18:16,831 - root - INFO - New connection from: 192.168.56.1
2022-02-24 15:18:17,179 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner[WinError 10053] An established connection was aborted by the software in your host machine
2022-02-24 15:18:17,183 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-24 15:18:17,183 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-24 15:18:17,187 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-24 15:18:17,187 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-24 15:18:17,187 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-24 15:18:17,187 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 607, in _read_timeout
2022-02-24 15:18:17,187 - paramiko.transport - ERROR -     x = self.__socket.recv(128)
2022-02-24 15:18:17,187 - paramiko.transport - ERROR - ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2022-02-24 15:18:17,187 - paramiko.transport - ERROR - 
2022-02-24 15:18:17,187 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-24 15:18:17,188 - paramiko.transport - ERROR - 
2022-02-24 15:18:17,188 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-24 15:18:17,188 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-24 15:18:17,188 - paramiko.transport - ERROR -     self._check_banner()
2022-02-24 15:18:17,188 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-24 15:18:17,188 - paramiko.transport - ERROR -     raise SSHException(
2022-02-24 15:18:17,188 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[WinError 10053] An established connection was aborted by the software in your host machine
2022-02-24 15:18:17,188 - paramiko.transport - ERROR - 
2022-02-24 15:21:17,111 - root - INFO - New connection from: 192.168.56.1
2022-02-24 15:21:17,112 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-24 15:21:17,142 - paramiko.transport - INFO - Auth rejected (none).
2022-02-24 15:21:17,142 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-24 15:21:19,634 - root - INFO - new client credentials (192.168.56.1): username: kali, password: kali
2022-02-24 15:21:19,634 - paramiko.transport - INFO - Auth granted (password).
2022-02-24 15:21:19,636 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-24 15:21:19,637 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-24 15:21:19,637 - root - INFO - Client compression (192.168.56.1): none
2022-02-24 15:21:19,638 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-24 15:21:19,638 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-24 15:21:26,813 - root - INFO - Command receied (192.168.56.1): dir
2022-02-24 15:21:26,909 - root - INFO - Response -> honeypot (192.168.56.1) 22-02-2022  03:43 PM    <DIR>          .
24-10-2021  08:24 PM    <DIR>          ..
07-12-2021  08:32 PM    <DIR>          .android
22-09-2020  03:43 PM    <DIR>          3D Objects
15-10-2020  04:12 PM    <DIR>          ansel
07-01-2022  12:44 AM            85,815 battery-report.html
24-10-2021  09:06 PM    <DIR>          Contacts
20-02-2022  08:57 AM    <DIR>          Desktop
27-01-2022  05:42 PM    <DIR>          Documents
23-02-2022  03:52 PM    <DIR>          Downloads
08-12-2021  04:24 PM    <DIR>          Dropbox
08-02-2022  03:44 PM               703 ll.txt
24-10-2021  09:06 PM    <DIR>          Music
30-12-2021  11:42 PM    <DIR>          New Folder
24-12-2021  11:30 PM    <DIR>          Pictures
24-10-2021  09:06 PM    <DIR>          Saved Games
09-01-2022  07:02 PM               142 test.html
31-10-2021  12:27 PM    <DIR>          Videos
              3 File(s)         92,152 bytes
              15 Dir(s)  52,386,295,808 bytes free
2022-02-24 15:21:33,230 - root - INFO - Command receied (192.168.56.1): cd
2022-02-24 15:21:33,230 - root - INFO - Response -> honeypot (192.168.56.1) /root/user
2022-02-24 15:21:37,413 - root - INFO - Command receied (192.168.56.1): exit
2022-02-24 15:21:37,413 - root - INFO - Connection closed (via exit command): 192.168.56.1

2022-02-24 15:21:37,415 - paramiko.transport - INFO - Disconnect (code 11): disconnected by user
2022-02-27 00:14:36,510 - root - INFO - New connection from: 192.168.56.1
2022-02-27 00:14:36,608 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 00:14:36,617 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 00:14:36,619 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 00:14:36,619 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 00:14:36,619 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 00:14:36,620 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 00:14:36,620 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 00:14:36,620 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 00:14:36,620 - paramiko.transport - ERROR - EOFError
2022-02-27 00:14:36,620 - paramiko.transport - ERROR - 
2022-02-27 00:14:36,620 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 00:14:36,621 - paramiko.transport - ERROR - 
2022-02-27 00:14:36,621 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 00:14:36,621 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 00:14:36,621 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 00:14:36,621 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 00:14:36,621 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 00:14:36,621 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 00:14:36,621 - paramiko.transport - ERROR - 
2022-02-27 00:14:36,624 - root - INFO - New connection from: 192.168.56.1
2022-02-27 00:14:37,750 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 00:14:37,750 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 00:14:37,758 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 00:14:37,758 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 00:14:37,758 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 00:14:37,758 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 00:14:37,758 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 00:14:37,758 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 00:14:37,759 - paramiko.transport - ERROR - EOFError
2022-02-27 00:14:37,759 - paramiko.transport - ERROR - 
2022-02-27 00:14:37,759 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 00:14:37,759 - paramiko.transport - ERROR - 
2022-02-27 00:14:37,777 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 00:14:37,777 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 00:14:37,777 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 00:14:37,777 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 00:14:37,777 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 00:14:37,777 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 00:14:37,777 - paramiko.transport - ERROR - 
2022-02-27 00:14:37,777 - root - INFO - New connection from: 192.168.56.1
2022-02-27 00:14:41,142 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 00:14:41,142 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 00:14:41,142 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 00:14:41,142 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 00:14:41,142 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 00:14:41,142 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 00:14:41,142 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 00:14:41,142 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 00:14:41,142 - paramiko.transport - ERROR - EOFError
2022-02-27 00:14:41,142 - paramiko.transport - ERROR - 
2022-02-27 00:14:41,142 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 00:14:41,142 - paramiko.transport - ERROR - 
2022-02-27 00:14:41,142 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 00:14:41,142 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 00:14:41,142 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 00:14:41,142 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 00:14:41,142 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 00:14:41,142 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 00:14:41,142 - paramiko.transport - ERROR - 
2022-02-27 00:14:42,807 - root - INFO - New connection from: 192.168.56.1
2022-02-27 00:14:42,811 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 00:14:42,812 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 00:14:42,812 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 00:14:42,813 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 00:14:42,813 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 00:14:42,813 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 00:14:42,813 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 00:14:42,813 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 00:14:42,813 - paramiko.transport - ERROR - EOFError
2022-02-27 00:14:42,814 - paramiko.transport - ERROR - 
2022-02-27 00:14:42,814 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 00:14:42,814 - paramiko.transport - ERROR - 
2022-02-27 00:14:42,814 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 00:14:42,814 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 00:14:42,814 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 00:14:42,814 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 00:14:42,814 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 00:14:42,815 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 00:14:42,815 - paramiko.transport - ERROR - 
2022-02-27 00:14:42,818 - root - INFO - New connection from: 192.168.56.1
2022-02-27 00:14:57,870 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 00:14:57,870 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 00:14:57,870 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 00:14:57,870 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 00:14:57,870 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 00:14:57,870 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 00:14:57,870 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 622, in _read_timeout
2022-02-27 00:14:57,870 - paramiko.transport - ERROR -     raise socket.timeout()
2022-02-27 00:14:57,870 - paramiko.transport - ERROR - socket.timeout
2022-02-27 00:14:57,870 - paramiko.transport - ERROR - 
2022-02-27 00:14:57,870 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 00:14:57,870 - paramiko.transport - ERROR - 
2022-02-27 00:14:57,870 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 00:14:57,870 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 00:14:57,870 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 00:14:57,870 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 00:14:57,870 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 00:14:57,870 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 00:14:57,870 - paramiko.transport - ERROR - 
2022-02-27 00:59:46,692 - root - INFO - New connection from: 192.168.56.1
2022-02-27 00:59:47,030 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner[WinError 10053] An established connection was aborted by the software in your host machine
2022-02-27 00:59:47,038 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 00:59:47,039 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 00:59:47,039 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 00:59:47,039 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 00:59:47,039 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 00:59:47,039 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 607, in _read_timeout
2022-02-27 00:59:47,040 - paramiko.transport - ERROR -     x = self.__socket.recv(128)
2022-02-27 00:59:47,040 - paramiko.transport - ERROR - ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2022-02-27 00:59:47,040 - paramiko.transport - ERROR - 
2022-02-27 00:59:47,040 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 00:59:47,040 - paramiko.transport - ERROR - 
2022-02-27 00:59:47,040 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 00:59:47,040 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 00:59:47,040 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 00:59:47,041 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 00:59:47,041 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 00:59:47,041 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[WinError 10053] An established connection was aborted by the software in your host machine
2022-02-27 00:59:47,041 - paramiko.transport - ERROR - 
2022-02-27 01:01:13,588 - root - INFO - New connection from: 192.168.56.1
2022-02-27 01:01:13,590 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-27 01:01:13,627 - paramiko.transport - INFO - Auth rejected (none).
2022-02-27 01:01:13,627 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-27 01:02:09,151 - root - INFO - New connection from: 192.168.56.1
2022-02-27 01:02:09,153 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-27 01:02:09,173 - paramiko.transport - INFO - Auth rejected (none).
2022-02-27 01:02:09,173 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-27 01:02:12,209 - root - INFO - new client credentials (192.168.56.1): username: kali, password: kali
2022-02-27 01:02:12,209 - paramiko.transport - INFO - Auth granted (password).
2022-02-27 01:02:12,213 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-27 01:02:12,214 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-27 01:02:12,215 - root - INFO - Client compression (192.168.56.1): none
2022-02-27 01:02:12,215 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-27 01:02:12,215 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-27 01:02:35,783 - root - INFO - Command receied (192.168.56.1): okc    
2022-02-27 01:02:38,924 - root - INFO - Command receied (192.168.56.1): jai
2022-02-27 01:02:40,811 - root - INFO - Command receied (192.168.56.1): ok
2022-02-27 01:02:43,016 - root - INFO - Command receied (192.168.56.1): cmd
2022-02-27 01:02:46,170 - root - INFO - Command receied (192.168.56.1): pwd
2022-02-27 01:02:48,418 - root - INFO - Command receied (192.168.56.1): cd
2022-02-27 01:02:48,419 - root - INFO - Response -> honeypot (192.168.56.1) /root/user
2022-02-27 01:02:54,442 - root - INFO - Command receied (192.168.56.1): ls
2022-02-27 01:02:57,974 - root - INFO - Command receied (192.168.56.1): dir
2022-02-27 01:02:57,987 - root - INFO - Response -> honeypot (192.168.56.1) 22-02-2022  03:43 PM    <DIR>          .
24-10-2021  08:24 PM    <DIR>          ..
07-12-2021  08:32 PM    <DIR>          .android
22-09-2020  03:43 PM    <DIR>          3D Objects
15-10-2020  04:12 PM    <DIR>          ansel
07-01-2022  12:44 AM            85,815 battery-report.html
24-10-2021  09:06 PM    <DIR>          Contacts
20-02-2022  08:57 AM    <DIR>          Desktop
27-01-2022  05:42 PM    <DIR>          Documents
23-02-2022  03:52 PM    <DIR>          Downloads
08-12-2021  04:24 PM    <DIR>          Dropbox
08-02-2022  03:44 PM               703 ll.txt
24-10-2021  09:06 PM    <DIR>          Music
30-12-2021  11:42 PM    <DIR>          New Folder
24-12-2021  11:30 PM    <DIR>          Pictures
24-10-2021  09:06 PM    <DIR>          Saved Games
09-01-2022  07:02 PM               142 test.html
31-10-2021  12:27 PM    <DIR>          Videos
              3 File(s)         92,152 bytes
              15 Dir(s)  52,386,295,808 bytes free
2022-02-27 01:03:06,137 - root - INFO - Command receied (192.168.56.1): exit
2022-02-27 01:03:06,137 - root - INFO - Connection closed (via exit command): 192.168.56.1

2022-02-27 01:03:06,140 - paramiko.transport - INFO - Disconnect (code 11): disconnected by user
2022-02-27 01:06:03,201 - root - INFO - New connection from: 192.168.56.1
2022-02-27 01:06:03,206 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-27 01:06:03,236 - paramiko.transport - INFO - Auth rejected (none).
2022-02-27 01:06:03,237 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-27 01:06:05,897 - root - INFO - new client credentials (192.168.56.1): username: kali, password: kali
2022-02-27 01:06:05,897 - paramiko.transport - INFO - Auth granted (password).
2022-02-27 01:06:05,899 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-27 01:06:05,899 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-27 01:06:05,900 - root - INFO - Client compression (192.168.56.1): none
2022-02-27 01:06:05,900 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-27 01:06:05,901 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-27 01:06:08,894 - root - INFO - Command receied (192.168.56.1): exit
2022-02-27 01:06:08,895 - root - INFO - Connection closed (via exit command): 192.168.56.1

2022-02-27 01:06:08,897 - paramiko.transport - INFO - Disconnect (code 11): disconnected by user
2022-02-27 01:06:53,881 - root - INFO - New connection from: 192.168.56.1
2022-02-27 01:06:53,883 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-27 01:06:53,907 - paramiko.transport - INFO - Auth rejected (none).
2022-02-27 01:06:53,907 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-27 01:06:55,717 - root - INFO - new client credentials (192.168.56.1): username: kali, password: kli
2022-02-27 01:06:55,717 - paramiko.transport - INFO - Auth granted (password).
2022-02-27 01:06:55,719 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-27 01:06:55,720 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-27 01:06:55,720 - root - INFO - Client compression (192.168.56.1): none
2022-02-27 01:06:55,720 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-27 01:06:55,720 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-27 01:06:59,193 - root - INFO - Command receied (192.168.56.1): exit
2022-02-27 01:06:59,194 - root - INFO - Connection closed (via exit command): 192.168.56.1

2022-02-27 01:06:59,199 - paramiko.transport - INFO - Disconnect (code 11): disconnected by user
2022-02-27 01:14:30,502 - root - INFO - New connection from: 192.168.56.1
2022-02-27 01:14:30,509 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-27 01:14:30,537 - paramiko.transport - INFO - Auth rejected (none).
2022-02-27 01:14:30,537 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-27 01:14:32,970 - root - INFO - new client credentials (192.168.56.1): username: kali, password: kali
2022-02-27 01:14:32,970 - paramiko.transport - INFO - Auth granted (password).
2022-02-27 01:14:32,973 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-27 01:14:32,973 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-27 01:14:32,973 - root - INFO - Client compression (192.168.56.1): none
2022-02-27 01:14:32,974 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-27 01:14:32,974 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-27 01:16:26,171 - root - INFO - New connection from: 192.168.56.1
2022-02-27 01:16:26,177 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-27 01:16:26,209 - paramiko.transport - INFO - Auth rejected (none).
2022-02-27 01:16:26,209 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-27 01:16:28,370 - root - INFO - new client credentials (192.168.56.1): username: kali, password: li
2022-02-27 01:16:28,370 - paramiko.transport - INFO - Auth granted (password).
2022-02-27 01:16:28,374 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-27 01:16:28,375 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-27 01:16:28,376 - root - INFO - Client compression (192.168.56.1): none
2022-02-27 01:16:28,376 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-27 01:16:28,377 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-27 09:02:42,829 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:02:42,829 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:02:42,834 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:02:42,841 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:02:42,841 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:02:42,841 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:02:42,841 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:02:42,841 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:02:42,841 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:02:42,841 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:02:42,841 - paramiko.transport - ERROR - EOFError
2022-02-27 09:02:42,841 - paramiko.transport - ERROR - 
2022-02-27 09:02:42,841 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:02:42,841 - paramiko.transport - ERROR - 
2022-02-27 09:02:42,841 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:02:42,841 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:02:42,841 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:02:42,841 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:02:42,841 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:02:42,841 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:02:42,841 - paramiko.transport - ERROR - 
2022-02-27 09:02:43,987 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:02:43,997 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:02:43,997 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:02:43,997 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:02:43,997 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:02:43,997 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:02:43,997 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:02:43,997 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:02:43,997 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:02:43,997 - paramiko.transport - ERROR - EOFError
2022-02-27 09:02:43,997 - paramiko.transport - ERROR - 
2022-02-27 09:02:43,997 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:02:43,997 - paramiko.transport - ERROR - 
2022-02-27 09:02:43,997 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:02:43,997 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:02:43,997 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:02:43,997 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:02:43,997 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:02:43,997 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:02:43,997 - paramiko.transport - ERROR - 
2022-02-27 09:02:48,721 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:02:48,722 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:02:48,722 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:02:48,722 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:02:48,722 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:02:48,723 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:02:48,723 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:02:48,723 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:02:48,723 - paramiko.transport - ERROR - EOFError
2022-02-27 09:02:48,723 - paramiko.transport - ERROR - 
2022-02-27 09:02:48,723 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:02:48,723 - paramiko.transport - ERROR - 
2022-02-27 09:02:48,723 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:02:48,724 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:02:48,724 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:02:48,724 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:02:48,724 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:02:48,724 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:02:48,724 - paramiko.transport - ERROR - 
2022-02-27 09:02:49,027 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:02:49,029 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:02:49,031 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:02:49,033 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:02:49,034 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:02:49,034 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:02:49,034 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:02:49,034 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:02:49,034 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:02:49,034 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:02:49,034 - paramiko.transport - ERROR - EOFError
2022-02-27 09:02:49,034 - paramiko.transport - ERROR - 
2022-02-27 09:02:49,034 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:02:49,034 - paramiko.transport - ERROR - 
2022-02-27 09:02:49,034 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:02:49,034 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:02:49,034 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:02:49,034 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:02:49,034 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:02:49,034 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:02:49,034 - paramiko.transport - ERROR - 
2022-02-27 09:02:58,739 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:02:58,740 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:02:58,740 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:02:58,740 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:02:58,740 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:02:58,740 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:02:58,740 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:02:58,740 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:02:58,740 - paramiko.transport - ERROR - EOFError
2022-02-27 09:02:58,740 - paramiko.transport - ERROR - 
2022-02-27 09:02:58,740 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:02:58,740 - paramiko.transport - ERROR - 
2022-02-27 09:02:58,740 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:02:58,740 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:02:58,740 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:02:58,740 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:02:58,839 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:02:58,839 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:02:58,839 - paramiko.transport - ERROR - 
2022-02-27 09:50:46,722 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:50:46,722 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:50:46,734 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:50:46,735 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:50:46,735 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:50:46,736 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:50:46,736 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:50:46,736 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:50:46,736 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:50:46,736 - paramiko.transport - ERROR - EOFError
2022-02-27 09:50:46,736 - paramiko.transport - ERROR - 
2022-02-27 09:50:46,737 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:50:46,737 - paramiko.transport - ERROR - 
2022-02-27 09:50:46,737 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:50:46,737 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:50:46,737 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:50:46,738 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:50:46,738 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:50:46,738 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:50:46,738 - paramiko.transport - ERROR - 
2022-02-27 09:50:46,743 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:50:47,863 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:50:47,866 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:50:47,866 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:50:47,866 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:50:47,866 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:50:47,866 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:50:47,867 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:50:47,867 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:50:47,867 - paramiko.transport - ERROR - EOFError
2022-02-27 09:50:47,867 - paramiko.transport - ERROR - 
2022-02-27 09:50:47,867 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:50:47,867 - paramiko.transport - ERROR - 
2022-02-27 09:50:47,867 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:50:47,867 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:50:47,868 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:50:47,868 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:50:47,868 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:50:47,868 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:50:47,868 - paramiko.transport - ERROR - 
2022-02-27 09:50:47,872 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:50:52,928 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:50:52,928 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:50:52,928 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:50:52,928 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:50:52,928 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:50:52,934 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:50:52,934 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:50:52,934 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:50:52,934 - paramiko.transport - ERROR - EOFError
2022-02-27 09:50:52,934 - paramiko.transport - ERROR - 
2022-02-27 09:50:52,935 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:50:52,935 - paramiko.transport - ERROR - 
2022-02-27 09:50:52,935 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:50:52,935 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:50:52,935 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:50:52,935 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:50:52,936 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:50:52,936 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:50:52,936 - paramiko.transport - ERROR - 
2022-02-27 09:50:52,939 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:51:08,022 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:51:08,022 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:51:08,022 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:51:08,022 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:51:08,022 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:51:08,022 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:51:08,022 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 622, in _read_timeout
2022-02-27 09:51:08,022 - paramiko.transport - ERROR -     raise socket.timeout()
2022-02-27 09:51:08,022 - paramiko.transport - ERROR - socket.timeout
2022-02-27 09:51:08,022 - paramiko.transport - ERROR - 
2022-02-27 09:51:08,022 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:51:08,022 - paramiko.transport - ERROR - 
2022-02-27 09:51:08,022 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:51:08,022 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:51:08,022 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:51:08,022 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:51:08,022 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:51:08,022 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:51:08,022 - paramiko.transport - ERROR - 
2022-02-27 09:51:34,178 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:51:34,178 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:51:34,178 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:51:34,186 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:51:34,186 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:51:34,186 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:51:34,186 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:51:34,186 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:51:34,186 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:51:34,186 - paramiko.transport - ERROR - EOFError
2022-02-27 09:51:34,186 - paramiko.transport - ERROR - 
2022-02-27 09:51:34,186 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:51:34,186 - paramiko.transport - ERROR - 
2022-02-27 09:51:34,186 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:51:34,186 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:51:34,186 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:51:34,186 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:51:34,186 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:51:34,186 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:51:34,186 - paramiko.transport - ERROR - 
2022-02-27 09:51:34,190 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:51:35,261 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:51:35,261 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:51:35,261 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:51:35,261 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:51:35,261 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:51:35,269 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:51:35,269 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:51:35,269 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:51:35,269 - paramiko.transport - ERROR - EOFError
2022-02-27 09:51:35,269 - paramiko.transport - ERROR - 
2022-02-27 09:51:35,269 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:51:35,269 - paramiko.transport - ERROR - 
2022-02-27 09:51:35,269 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:51:35,269 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:51:35,269 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:51:35,269 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:51:35,269 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:51:35,269 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:51:35,269 - paramiko.transport - ERROR - 
2022-02-27 09:51:35,272 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:51:40,328 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:51:40,328 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:51:40,328 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:51:40,328 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:51:40,328 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:51:40,328 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:51:40,328 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:51:40,335 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:51:40,335 - paramiko.transport - ERROR - EOFError
2022-02-27 09:51:40,335 - paramiko.transport - ERROR - 
2022-02-27 09:51:40,335 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:51:40,335 - paramiko.transport - ERROR - 
2022-02-27 09:51:40,335 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:51:40,335 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:51:40,335 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:51:40,335 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:51:40,335 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:51:40,336 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:51:40,336 - paramiko.transport - ERROR - 
2022-02-27 09:51:40,341 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:52:10,375 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:52:10,382 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:52:10,385 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:52:10,385 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:52:10,385 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:52:10,385 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:52:10,385 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:52:10,385 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:52:10,386 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:52:10,386 - paramiko.transport - ERROR - EOFError
2022-02-27 09:52:10,386 - paramiko.transport - ERROR - 
2022-02-27 09:52:10,387 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:52:10,387 - paramiko.transport - ERROR - 
2022-02-27 09:52:10,387 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:52:10,387 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:52:10,387 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:52:10,387 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:52:10,387 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:52:10,387 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:52:10,387 - paramiko.transport - ERROR - 
2022-02-27 09:52:10,389 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:52:11,318 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:52:11,318 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:52:11,318 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:52:11,318 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:52:11,318 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:52:11,318 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:52:11,318 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:52:11,318 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:52:11,318 - paramiko.transport - ERROR - EOFError
2022-02-27 09:52:11,318 - paramiko.transport - ERROR - 
2022-02-27 09:52:11,318 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:52:11,318 - paramiko.transport - ERROR - 
2022-02-27 09:52:11,318 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:52:11,318 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:52:11,318 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:52:11,318 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:52:11,318 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:52:11,318 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:52:11,318 - paramiko.transport - ERROR - 
2022-02-27 09:52:11,318 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:52:26,327 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:52:26,327 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:52:26,327 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:52:26,327 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:52:26,327 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:52:26,327 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:52:26,327 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 622, in _read_timeout
2022-02-27 09:52:26,327 - paramiko.transport - ERROR -     raise socket.timeout()
2022-02-27 09:52:26,327 - paramiko.transport - ERROR - socket.timeout
2022-02-27 09:52:26,327 - paramiko.transport - ERROR - 
2022-02-27 09:52:26,327 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:52:26,327 - paramiko.transport - ERROR - 
2022-02-27 09:52:26,327 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:52:26,327 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:52:26,327 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:52:26,327 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:52:26,327 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:52:26,327 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:52:26,327 - paramiko.transport - ERROR - 
2022-02-27 09:52:55,764 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:52:55,767 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:52:55,767 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:52:55,767 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:52:55,767 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:52:55,767 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:52:55,767 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:52:55,767 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:52:55,767 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:52:55,767 - paramiko.transport - ERROR - EOFError
2022-02-27 09:52:55,767 - paramiko.transport - ERROR - 
2022-02-27 09:52:55,767 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:52:55,767 - paramiko.transport - ERROR - 
2022-02-27 09:52:55,767 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:52:55,767 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:52:55,767 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:52:55,767 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:52:55,767 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:52:55,767 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:52:55,767 - paramiko.transport - ERROR - 
2022-02-27 09:53:26,920 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:53:41,945 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:53:41,945 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:53:41,945 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:53:41,945 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:53:41,945 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:53:41,945 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:53:41,945 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 622, in _read_timeout
2022-02-27 09:53:41,945 - paramiko.transport - ERROR -     raise socket.timeout()
2022-02-27 09:53:41,945 - paramiko.transport - ERROR - socket.timeout
2022-02-27 09:53:41,945 - paramiko.transport - ERROR - 
2022-02-27 09:53:41,945 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:53:41,945 - paramiko.transport - ERROR - 
2022-02-27 09:53:41,945 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:53:41,945 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:53:41,945 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:53:41,945 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:53:41,945 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:53:41,945 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:53:41,945 - paramiko.transport - ERROR - 
2022-02-27 09:53:41,945 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:53:41,945 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:53:41,954 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:53:41,954 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:53:41,954 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:53:41,954 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:53:41,954 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:53:41,954 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:53:41,954 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:53:41,954 - paramiko.transport - ERROR - EOFError
2022-02-27 09:53:41,954 - paramiko.transport - ERROR - 
2022-02-27 09:53:41,954 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:53:41,954 - paramiko.transport - ERROR - 
2022-02-27 09:53:41,954 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:53:41,954 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:53:41,954 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:53:41,954 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:53:41,954 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:53:41,954 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:53:41,954 - paramiko.transport - ERROR - 
2022-02-27 09:54:28,846 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:54:28,846 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:54:28,846 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:54:28,855 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:54:28,855 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:54:28,855 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:54:28,855 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:54:28,855 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:54:28,855 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:54:28,855 - paramiko.transport - ERROR - EOFError
2022-02-27 09:54:28,855 - paramiko.transport - ERROR - 
2022-02-27 09:54:28,855 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:54:28,855 - paramiko.transport - ERROR - 
2022-02-27 09:54:28,855 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:54:28,855 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:54:28,855 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:54:28,855 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:54:28,855 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:54:28,855 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:54:28,855 - paramiko.transport - ERROR - 
2022-02-27 09:54:28,859 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:54:29,801 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:54:29,801 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:54:29,801 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:54:29,801 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:54:29,801 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:54:29,801 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:54:29,801 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:54:29,801 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:54:29,801 - paramiko.transport - ERROR - EOFError
2022-02-27 09:54:29,801 - paramiko.transport - ERROR - 
2022-02-27 09:54:29,801 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:54:29,801 - paramiko.transport - ERROR - 
2022-02-27 09:54:29,801 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:54:29,801 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:54:29,801 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:54:29,801 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:54:29,801 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:54:29,801 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:54:29,801 - paramiko.transport - ERROR - 
2022-02-27 09:54:29,807 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:55:52,841 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:55:52,841 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:55:52,851 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:55:52,852 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:55:52,852 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:55:52,852 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:55:52,852 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:55:52,852 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:55:52,852 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:55:52,852 - paramiko.transport - ERROR - EOFError
2022-02-27 09:55:52,852 - paramiko.transport - ERROR - 
2022-02-27 09:55:52,853 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:55:52,853 - paramiko.transport - ERROR - 
2022-02-27 09:55:52,853 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:55:52,853 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:55:52,853 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:55:52,853 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:55:52,853 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:55:52,853 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:55:52,853 - paramiko.transport - ERROR - 
2022-02-27 09:55:52,856 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:55:53,920 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:55:53,926 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:55:53,926 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:55:53,926 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:55:53,926 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:55:53,926 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:55:53,926 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:55:53,926 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:55:53,926 - paramiko.transport - ERROR - EOFError
2022-02-27 09:55:53,926 - paramiko.transport - ERROR - 
2022-02-27 09:55:53,926 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:55:53,930 - paramiko.transport - ERROR - 
2022-02-27 09:55:53,930 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:55:53,930 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:55:53,930 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:55:53,930 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:55:53,931 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:55:53,931 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:55:53,931 - paramiko.transport - ERROR - 
2022-02-27 09:55:53,932 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:55:58,981 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:55:58,981 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:55:58,982 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:55:58,982 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:55:58,982 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:55:58,982 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:55:58,982 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:55:58,982 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:55:58,983 - paramiko.transport - ERROR - EOFError
2022-02-27 09:55:58,983 - paramiko.transport - ERROR - 
2022-02-27 09:55:58,983 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:55:58,983 - paramiko.transport - ERROR - 
2022-02-27 09:55:58,983 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:55:58,983 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:55:58,983 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:55:58,983 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:55:58,983 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:55:58,983 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:55:58,983 - paramiko.transport - ERROR - 
2022-02-27 09:55:58,988 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:56:03,872 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:56:03,872 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:56:03,872 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:56:03,872 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:56:03,872 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:56:03,872 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:56:03,872 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:56:03,872 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:56:03,872 - paramiko.transport - ERROR - EOFError
2022-02-27 09:56:03,872 - paramiko.transport - ERROR - 
2022-02-27 09:56:03,872 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:56:03,872 - paramiko.transport - ERROR - 
2022-02-27 09:56:03,872 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:56:03,872 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:56:03,872 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:56:03,872 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:56:03,872 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:56:03,872 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:56:03,872 - paramiko.transport - ERROR - 
2022-02-27 09:57:11,295 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:57:11,299 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:57:11,303 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:57:11,303 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:57:11,303 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:57:11,303 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:57:11,303 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:57:11,303 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:57:11,307 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:57:11,307 - paramiko.transport - ERROR - EOFError
2022-02-27 09:57:11,307 - paramiko.transport - ERROR - 
2022-02-27 09:57:11,307 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:57:11,307 - paramiko.transport - ERROR - 
2022-02-27 09:57:11,308 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:57:11,308 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:57:11,308 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:57:11,308 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:57:11,308 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:57:11,309 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:57:11,309 - paramiko.transport - ERROR - 
2022-02-27 09:57:11,312 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:57:12,365 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:57:12,365 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:57:12,365 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:57:12,365 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:57:12,365 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:57:12,365 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:57:12,365 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:57:12,365 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:57:12,365 - paramiko.transport - ERROR - EOFError
2022-02-27 09:57:12,365 - paramiko.transport - ERROR - 
2022-02-27 09:57:12,365 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:57:12,365 - paramiko.transport - ERROR - 
2022-02-27 09:57:12,365 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:57:12,365 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:57:12,365 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:57:12,365 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:57:12,365 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:57:12,365 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:57:12,365 - paramiko.transport - ERROR - 
2022-02-27 09:57:12,378 - root - INFO - New connection from: 192.168.56.1
2022-02-27 09:57:17,410 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner
2022-02-27 09:57:17,418 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:57:17,418 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 09:57:17,418 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 09:57:17,418 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 09:57:17,418 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 09:57:17,418 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 609, in _read_timeout
2022-02-27 09:57:17,418 - paramiko.transport - ERROR -     raise EOFError()
2022-02-27 09:57:17,418 - paramiko.transport - ERROR - EOFError
2022-02-27 09:57:17,418 - paramiko.transport - ERROR - 
2022-02-27 09:57:17,418 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 09:57:17,418 - paramiko.transport - ERROR - 
2022-02-27 09:57:17,420 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 09:57:17,420 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 09:57:17,420 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 09:57:17,420 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 09:57:17,420 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 09:57:17,420 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner
2022-02-27 09:57:17,420 - paramiko.transport - ERROR - 
2022-02-27 09:57:17,423 - root - INFO - New connection from: 192.168.56.1
2022-02-27 12:53:44,211 - root - INFO - New connection from: 192.168.56.1
2022-02-27 12:53:44,552 - paramiko.transport - ERROR - Exception (server): Error reading SSH protocol banner[WinError 10053] An established connection was aborted by the software in your host machine
2022-02-27 12:53:44,571 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 12:53:44,571 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2270, in _check_banner
2022-02-27 12:53:44,571 - paramiko.transport - ERROR -     buf = self.packetizer.readline(timeout)
2022-02-27 12:53:44,571 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 380, in readline
2022-02-27 12:53:44,571 - paramiko.transport - ERROR -     buf += self._read_timeout(timeout)
2022-02-27 12:53:44,571 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\packet.py", line 607, in _read_timeout
2022-02-27 12:53:44,571 - paramiko.transport - ERROR -     x = self.__socket.recv(128)
2022-02-27 12:53:44,571 - paramiko.transport - ERROR - ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
2022-02-27 12:53:44,571 - paramiko.transport - ERROR - 
2022-02-27 12:53:44,571 - paramiko.transport - ERROR - During handling of the above exception, another exception occurred:
2022-02-27 12:53:44,571 - paramiko.transport - ERROR - 
2022-02-27 12:53:44,571 - paramiko.transport - ERROR - Traceback (most recent call last):
2022-02-27 12:53:44,571 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2093, in run
2022-02-27 12:53:44,572 - paramiko.transport - ERROR -     self._check_banner()
2022-02-27 12:53:44,572 - paramiko.transport - ERROR -   File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\paramiko\transport.py", line 2274, in _check_banner
2022-02-27 12:53:44,572 - paramiko.transport - ERROR -     raise SSHException(
2022-02-27 12:53:44,572 - paramiko.transport - ERROR - paramiko.ssh_exception.SSHException: Error reading SSH protocol banner[WinError 10053] An established connection was aborted by the software in your host machine
2022-02-27 12:53:44,572 - paramiko.transport - ERROR - 
2022-02-27 12:54:05,257 - root - INFO - New connection from: 192.168.56.1
2022-02-27 12:54:05,258 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-27 12:54:05,286 - paramiko.transport - INFO - Auth rejected (none).
2022-02-27 12:54:05,286 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-27 12:54:09,317 - root - INFO - new client credentials (192.168.56.1): username: kali, password: kali
2022-02-27 12:54:09,317 - paramiko.transport - INFO - Auth granted (password).
2022-02-27 12:54:09,319 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-27 12:54:09,320 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-27 12:54:09,320 - root - INFO - Client compression (192.168.56.1): none
2022-02-27 12:54:09,320 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-27 12:54:09,322 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-27 12:54:43,228 - root - INFO - New connection from: 192.168.56.1
2022-02-27 12:54:43,235 - paramiko.transport - INFO - Connected (version 2.0, client OpenSSH_8.4p1)
2022-02-27 12:54:43,252 - paramiko.transport - INFO - Auth rejected (none).
2022-02-27 12:54:43,252 - root - INFO - client called get_allowed_auths (192.168.56.1) with username kali
2022-02-27 12:54:44,779 - root - INFO - new client credentials (192.168.56.1): username: kali, password: kali
2022-02-27 12:54:44,779 - paramiko.transport - INFO - Auth granted (password).
2022-02-27 12:54:44,781 - root - INFO - client called check_channel_request (192.168.56.1): session
2022-02-27 12:54:44,783 - root - INFO - Client mac (192.168.56.1): hmac-sha2-256-etm@openssh.com
2022-02-27 12:54:44,784 - root - INFO - Client compression (192.168.56.1): none
2022-02-27 12:54:44,784 - root - INFO - Client SSH version (192.168.56.1): SSH-2.0-OpenSSH_8.4p1 Debian-5
2022-02-27 12:54:44,784 - root - INFO - Client SSH cipher (192.168.56.1): aes128-ctr
2022-02-27 12:54:47,835 - root - INFO - Command received (192.168.56.1): ls
2022-02-27 12:54:56,062 - root - INFO - Command received (192.168.56.1): [B[B[B[B[B[B[B[B[B[B[B[B
2022-02-27 12:54:58,203 - root - INFO - Command received (192.168.56.1): cd
2022-02-27 12:54:58,204 - root - INFO - Response -> honeypot (192.168.56.1) /root/user
2022-02-27 12:54:59,097 - root - INFO - Command received (192.168.56.1): dir
2022-02-27 12:54:59,107 - root - INFO - Response -> honeypot (192.168.56.1) 22-02-2022  03:43 PM    <DIR>          .
24-10-2021  08:24 PM    <DIR>          ..
07-12-2021  08:32 PM    <DIR>          .android
22-09-2020  03:43 PM    <DIR>          3D Objects
15-10-2020  04:12 PM    <DIR>          ansel
07-01-2022  12:44 AM            85,815 battery-report.html
24-10-2021  09:06 PM    <DIR>          Contacts
20-02-2022  08:57 AM    <DIR>          Desktop
27-01-2022  05:42 PM    <DIR>          Documents
23-02-2022  03:52 PM    <DIR>          Downloads
08-12-2021  04:24 PM    <DIR>          Dropbox
08-02-2022  03:44 PM               703 ll.txt
24-10-2021  09:06 PM    <DIR>          Music
30-12-2021  11:42 PM    <DIR>          New Folder
24-12-2021  11:30 PM    <DIR>          Pictures
24-10-2021  09:06 PM    <DIR>          Saved Games
09-01-2022  07:02 PM               142 test.html
31-10-2021  12:27 PM    <DIR>          Videos
              3 File(s)         92,152 bytes
              15 Dir(s)  52,386,295,808 bytes free
2022-02-27 12:55:05,831 - root - INFO - Command received (192.168.56.1): pwd
2022-02-27 12:55:09,751 - root - INFO - Command received (192.168.56.1): exit
2022-02-27 12:55:09,751 - root - INFO - Connection closed (via exit command): 192.168.56.1

2022-02-27 12:55:09,757 - paramiko.transport - INFO - Disconnect (code 11): disconnected by user
